[options]
    colorscheme = "palenight"
    colorscheme_bg = "dark"
    vimcompatible = true
    enable_guicolors = true
    enable_tabline_filetype_icon = true
    enable_statusline_mode = true
    statusline_unicode_symbols = true
    statusline_separator = 'fire'
    statusline_inactive_separator = "bar"
    buffer_index_type = 4
    windows_index_type = 3

[[layers]]
  name = 'colorscheme'

[[layers]]
  name = 'autocomplete'
  auto-completion-return-key-behavior = "complete"
  auto-completion-tab-key-behavior = "cycle"

[[layers]]
  name = 'shell'
  default_position = 'top'
  default_height = 30

[[layers]]
  name = "git"

[[layers]]
  name = "VersionControl"

[[layers]]
    name = "fzf"

[[layers]]
    name = "default"

[[layers]]
    name = "checkers"

[[layers]]
    name = "lang#python"

[[layers]]
    name = "lang#dockerfile"

[[layers]]
    name = "tools"
